crm114-20070807-BlameTheInterns-Ger-108 - SKS fixes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10052,6 +10052,177 @@ fi
 done
 
 
+
+for ac_header in endian.h sys/param.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  { echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## --------------------------------------------------- ##
+## Report this to crm114-general@lists.sourceforge.net ##
+## --------------------------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
+if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+ac_res=`eval echo '${'$as_ac_Header'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
+
+
+
 # see: http://www.gnu-pascal.de/crystal/gpc/en/mail11031.html
 
 for ac_header in crt_externs.h
@@ -18849,7 +19020,7 @@ CRM=":|crm"
 
 
 
-ac_config_files="$ac_config_files Makefile crm114.lsm docs/Makefile examples/Makefile mailfilter/Makefile man/Makefile man/include.zmm src/Makefile src/diff_em.sh tests/Makefile tests/aliustest.crm tests/approxtest.crm tests/argtest.crm tests/backwardstest.crm tests/beeptest.crm tests/bracktest.crm tests/classifytest.crm tests/escapetest.crm tests/eval_infiniteloop.crm tests/exectest.crm tests/fataltraptest.crm tests/inserttest_a.crm tests/inserttest_b.crm tests/inserttest_c.crm tests/learntest.crm tests/match_isolate_test.crm tests/matchtest.crm tests/mathalgtest.crm tests/mathrpntest.crm tests/nestaliustest.crm tests/overalterisolatedtest.crm tests/paolo_overvars.crm tests/randomiotest.crm tests/rewritetest.crm tests/skudtest.crm tests/statustest.crm tests/traptest.crm tests/uncaughttraptest.crm tests/unionintersecttest.crm tests/userdirtest.crm tests/windowtest.crm tests/windowtest_fromvar.crm tests/tenfold_validate.crm tests/tokendelimiterbugtest.crm tests/bracesbugtest.crm examples/pad.crm examples/shroud.crm mailfilter/classifymail.crm mailfilter/mailfilter.crm mailfilter/rewriteutil.crm"
+ac_config_files="$ac_config_files Makefile crm114.lsm docs/Makefile examples/Makefile mailfilter/Makefile man/Makefile man/include.zmm src/Makefile src/diff_em.sh src/indent.sh tests/Makefile tests/aliustest.crm tests/approxtest.crm tests/argtest.crm tests/backwardstest.crm tests/beeptest.crm tests/bracktest.crm tests/classifytest.crm tests/escapetest.crm tests/eval_infiniteloop.crm tests/exectest.crm tests/fataltraptest.crm tests/inserttest_a.crm tests/inserttest_b.crm tests/inserttest_c.crm tests/learntest.crm tests/match_isolate_test.crm tests/matchtest.crm tests/mathalgtest.crm tests/mathrpntest.crm tests/nestaliustest.crm tests/overalterisolatedtest.crm tests/paolo_overvars.crm tests/randomiotest.crm tests/rewritetest.crm tests/skudtest.crm tests/statustest.crm tests/traptest.crm tests/uncaughttraptest.crm tests/unionintersecttest.crm tests/userdirtest.crm tests/windowtest.crm tests/windowtest_fromvar.crm tests/tenfold_validate.crm tests/tokendelimiterbugtest.crm tests/bracesbugtest.crm examples/pad.crm examples/shroud.crm mailfilter/classifymail.crm mailfilter/mailfilter.crm mailfilter/rewriteutil.crm"
 
 
 cat >confcache <<\_ACEOF
@@ -19433,6 +19604,7 @@ do
     "man/include.zmm") CONFIG_FILES="$CONFIG_FILES man/include.zmm" ;;
     "src/Makefile") CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
     "src/diff_em.sh") CONFIG_FILES="$CONFIG_FILES src/diff_em.sh" ;;
+    "src/indent.sh") CONFIG_FILES="$CONFIG_FILES src/indent.sh" ;;
     "tests/Makefile") CONFIG_FILES="$CONFIG_FILES tests/Makefile" ;;
     "tests/aliustest.crm") CONFIG_FILES="$CONFIG_FILES tests/aliustest.crm" ;;
     "tests/approxtest.crm") CONFIG_FILES="$CONFIG_FILES tests/approxtest.crm" ;;
